export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as AnimatedBackground } from "./AnimatedBackground";
export { default as TechStack } from "./TechStack";
export { default as Projects } from "./Projects";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as ThreeScene } from "./ThreeScene";
export { default as CustomCursor } from "./CustomCursor";
